### ISSUE TITLE
[Arabic] Using Arabic_Legacy language the texts do not appear anymore

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#110]
Should duplicate the column in Gdrive and reimport all texts...
... or should we add a parameter in the Edition in order to override the language to use (for texts only)?

**Comment by CatmanIta** [comment]
Francesco requested a configuration toggle to use the arabic instead of arabic_legacy just for text items, but that can be confusionary:
- we have 3 language IDs in the configuration, it would need to be specified for each
- it is more of a hack

So, instead, we just put it into the code. If arabic_legacy text is required, instead we deliver the arabic text
