### ISSUE TITLE
MakeFriends - sometimes we have two correct letters

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura#135]
![image](https://user-images.githubusercontent.com/3244662/107484128-499eda80-6b82-11eb-9a0e-52fdf3de6442.png)

How should we handle this? @FrancyCavallari

**Comment by CatmanIta** [comment]
For what I see, the game advances only after you find both letters at this time, maybe that was on purpose?

**Comment by wassimbassil** [comment]
While playing I never had to choose 2  correct letters, even though the words contained more than 1 similar letter.
In this case, I wouldn't say the word has 2 common letters for the following reasons:
**ال**قمر (word on left) means THE Moon where **ال** is THE
whereas جمل simply is Camel
so in that case the letter ل should not be a correct answer because it does not form part of the original word قمر moon

**Comment by CatmanIta** [comment]
This should be fixed now, as the two forms will not be considered 'the same letter' anymore

**Comment by wassimbassil** [comment]
yes it is fixed!
