### ISSUE TITLE
[Arabic] Shaddah+Fahtah in "my_aunt_father" word is not using the offset set in DiacriticComboData  

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#172]
Check the word "my_aunt_father" and you'll notice the the offset between Shaddah and Fahath is wrong...
![image](https://user-images.githubusercontent.com/17926293/139153614-d8a9eb29-d216-4be2-8db3-d515de415533.png)

... and changing the values in DiacriticComboData Editor does not affect Fahtah position at all (only the Shaddah can be moved around).

The strangest thing about this bug is the the previous word "aunt_father" that has exactly the same letter+Shaddah+Fahtah combination works well!
![image](https://user-images.githubusercontent.com/17926293/139154348-e1b0e3eb-4a6a-4880-b3c0-f56fee9182c3.png)

**Comment by CatmanIta** [comment]
"Aunt_father" has the following unicodes and corresponding characters:

0639, 064E,       0645, 064E, 0651,      0629, 

ain fatha         meem fatha shadda     teh-marbuta


"My_aunt_father" has the following instead:


0639, 064E,    0645, 0651, 064E,        062A,   064A, 

ain fatha        meem shadda fatha      teh     yeh


The issue here is that the second one has the shadda in the wrong place, before the fatha and not after. 

In the shadda detection code we just check if it is *after* a diacritic, not before (as that was how it worked before), but it seems it is not always the case? Or is the shaddah tied to the letter, and not the diacritic in this case?

**Comment by CatmanIta** [comment]
It seems that you can combine them in any order, so I changed the parsing to handle the uncommon order too.

**Comment by wassimbassil** [comment]
Both words now have same correct offset
