### ISSUE TITLE
[Maze] Alef_madda never appears as the letter to write 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#206]
In Arabic Alef_madda was a LetterVariation, but for Dari I transformed it into a simple Letter...
... the only 2 things that it has "special/different from other letters are:
- its Number is 0 (according to our Dari literacy reference book it should appear as the first letter of the alphabet, so I set it to 0 not to change the numbers of all the Letters)
- its BaseLetter is set to "alef" while for all the other Letters the BaseLetter is the same letter

I hope it can help to identify why "alef_madda" seeems to be filtered out from the game

**Comment by FrancyCavallari** [comment]
I also notices that in other minigames it happens something similar (I.e. only 3 letters are playable in ColorTickle)...
... and that "alef_madda" gives an error when interacting with (in the activities in which it appears):
`Missing audio for alef_madda__lettername `

**Comment by CatmanIta** [comment]
It does appear in FastCrowd, which just uses the visuals. So I think it has to do with the missing audio. I'll check other games
![image](https://user-images.githubusercontent.com/3244662/147216130-00aca418-d713-41c9-b348-0dc480bb5aab.png)

**Comment by CatmanIta** [comment]
In ColorTickle, alef-madda is selected correctly, but the game uses only 6 rounds (i.e. 6 letters).
The QuestionBuilder is setup to get 10 letters. If not enough are found, it repeats the selection. It then orders them on difficulty as such:

[Teacher] - Generated Packs --------
1: Q []  OK(1) [(پ) pe; ]  NO(0) [] 
2: Q []  OK(1) [(ا) alef; ]  NO(0) [] 
3: Q []  OK(1) [(ب) be; ]  NO(0) [] 
4: Q []  OK(1) [(ت) te; ]  NO(0) [] 
5: Q []  OK(1) [(ا) alef; ]  NO(0) [] 
6: Q []  OK(1) [(و) vav; ]  NO(0) [] 
7: Q []  OK(1) [(آ) alef_madda; ]  NO(0) [] 
8: Q []  OK(1) [(ث) se; ]  NO(0) [] 
9: Q []  OK(1) [(آ) alef_madda; ]  NO(0) [] 
10: Q []  OK(1) [(پ) pe; ]  NO(0) [] 

So, alef_madda is always at the end! :)

I changed the builder to ask for 6 letters instead.

Ta da!

![image](https://user-images.githubusercontent.com/3244662/147217489-31edc320-84c8-4928-86bb-108035e2ab17.png)

**Comment by CatmanIta** [comment]
Please note that alef_madda has 1 as Complexity, while alef has 0.3

**Comment by CatmanIta** [comment]
The same happens in Maze. It requests 7 packs.

[Teacher] - Generated Packs --------
1: Q []  OK(1) [(پ) pe; ]  NO(0) [] 
2: Q []  OK(1) [(ت) te; ]  NO(0) [] 
3: Q []  OK(1) [(ب) be; ]  NO(0) [] 
4: Q []  OK(1) [(ا) alef; ]  NO(0) [] 
5: Q []  OK(1) [(ث) se; ]  NO(0) [] 
6: Q []  OK(1) [(و) vav; ]  NO(0) [] 
7: Q []  OK(1) [(آ) alef_madda; ]  NO(0) [] 

But the rounds are just 5! So it will never use alef_madda

Changing packs to 5 fixes the issue (and alef_madda is always last due to Complexity)

I think someday we'd better decide to make the rounds and requested packs the same number in all games, and make the content edition control that.
