### ISSUE TITLE
[DancingDots] "sukun" diacritic is not used in Dari... we should remove one of the buttons on the right

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#214]
![image](https://user-images.githubusercontent.com/17926293/146998993-e3d04134-59cb-4286-bcdc-452683ffc121.png)

**Comment by CatmanIta** [comment]
Since this is very specific to that language, I added a check in the game. If we are playing with the Dari learning language, Sukoun won't appear.

We may want in the future, if we want to use the game for other 'diacritics' such as accents, make it more dynamic and have each langauge list the diacritics it uses
