### ISSUE TITLE
Do you support Hindi and/or Filipino?

### ISSUE THREAD

**Issue by nya-elimu** [vgwb/Antura#275]

**Comment by FrancyCavallari** [comment]
Hello! 
Unfortunately we currently do not support neither Hindi nor Filipino...
... but we'd love to support them.

If you are interested in collaborating, helping us to suppoert those language we should definitely have a chat!

**Comment by nya-elimuai** [comment]
@FrancyCavallari Okay, thanks. 

Also, would it be possible to build a version of your game that uses only one language, instead of Spanish and English mixed together? (Targeting primary age children learning foundational literacy in their mother tongue, rather than learning a second language.)

**Comment by FrancyCavallari** [comment]
Yes! 
The Antura game was initially desgined as a Literacy tool (Early Grade Reading in the kids' mother language, originally in Arabic since it was designed for Syrian refugees) and then adapted to introduce a foreign language (like learning English from Spanish).
The current repository already supports both type of learning experiences and in a few weeks we plan to release a single Antura App that will include all editions we have currently available.
If you are interested to collaborate on the project or simply to use Antura with your students, maybe we should have a call and we can share more details with you,
Please write to info@vgwb.org and we'll get back to you ASAP...
