### ISSUE TITLE
[Home] Either Game_Title or Game_Title_2 should be called in the Home, depending of the edition

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#307]
Game_Title should be called for Learn To Read editions
Game_Title_2 should be called for Learn Language editions

Right now, it seems that the games always calls Game_Title_2... is it true?

NOTE: in Arabic_legacy the correct title (Antura and the Letters) uses the wrong filename (Game_Title_2)... so it should be renamed.

**Comment by CatmanIta** [comment]
True, Game_Title_2 is always called in the HomeScene (and KioskScene, but we cannot access that anymore)
I'll be changing so that the LearnMethod decides what localization ID to use.

Game_Title is called for games if there is no minigame Title setup, or if there is no Tutorial localization, for some reason. I'm getting rid of that.

Note that we also have Game_Title_3 and _4 but I have no idea where they are used (they aren't, it seems)

**Comment by CatmanIta** [comment]
(I also renamed arabic_legacy's file)
