### ISSUE TITLE
[Arabic] Playing Maze you get weird warning

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#333]
This one
`اﺳﺤﺐِ اﻟﻜﺮةَ إﻟﻰ اﻷﺳﻔﻞِ ﻟﺘﺸُﺪَّ اﻟﻤﻘﻼعَ ﺛﻢ ﺻَﻮِّب ﻋﻠﻰ اﻟﺤﺮفِ اﻟﺼﺤﻴﺢ.  has weird diacritic`

**Comment by CatmanIta** [comment]
This happens when the text has a weird placement of Shaddah and Diacritic. All our texts are generated withy the Diacritic first, and the Shaddah next, but who creates the text could input them in a different order, creating this warning. It should be just a warning, tho, so I am changing it. Should not break the text, but we should make sure to check how the shaddah and diacritics appear in that specific text!

**Comment by CatmanIta** [comment]
Warnign removed, everything is alright
