### ISSUE TITLE
[MissingLetter_phrase] The game gets stuck switching round from time to time 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#373]
![image](https://user-images.githubusercontent.com/17926293/174315832-bccdc050-7f55-4ffc-b52c-6160950f6538.png)

it was reported playing Learn Polish and it gives this error:
```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <6073cf49ed704e958b8a66d540dea948>:0)
Antura.Minigames.MissingLetter.RoundManager.RemoveWordfromQuestion (System.Collections.Generic.List`1[T] Words, Antura.LivingLetters.LL_WordData word) (at Assets/_games/MissingLetter/_scripts/RoundManager.cs:383)
Antura.Minigames.MissingLetter.RoundManager.NextSentenceQuestion () (at Assets/_games/MissingLetter/_scripts/RoundManager.cs:311)
Antura.Minigames.MissingLetter.RoundManager.NewRound () (at Assets/_games/MissingLetter/_scripts/RoundManager.cs:85)
Antura.Minigames.MissingLetter.MissingLetterPlayState.OnRoundResult (System.Boolean _result) (at Assets/_games/MissingLetter/_scripts/States/MissingLetterPlayState.cs:74)
Antura.Minigames.MissingLetter.RoundManager+<AnswerReactionCO>d__26.MoveNext () (at Assets/_games/MissingLetter/_scripts/RoundManager.cs:508)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <f1212ad1dec44ce7b7147976b91869c3>:0)


```

**Comment by ajzbrun** [comment]
I was looking for this issue but couldn't reproduce it. Anyway, as the exception says, is a problem of out of range when trying to remove a word from a question. The exception throws at line 383 of the script "RoundManager.cs".
A quick patch for the problem to stop appearing is the following 4 lines:

`if (index < 0)
                index = 0;
            else if (index > m_aoCurrentQuestionScene.Count)
                index = m_aoCurrentQuestionScene.Count;`

These previous lines just check if the generated index is between the range of the "m_aoCurrentQuestionScene" variable, and if not, sets the minimum or the maximum considering if the index was above or below the range.

Anyway, I didn't patch it and only leave this alternative here, because maybe @CatmanIta knows where exactly the problem is, and can make a better workaround.

**Comment by FrancyCavallari** [comment]
The problem is not happening in Learn English, for now I was only able to reproduce it playing Learn Polish...
... so I checked the phrases in Polish and there's one composed of only 2 words (Phrase_cheese : "Lubię SER").
Maybe this game requires at least 3 words to work fine?

**Comment by FrancyCavallari** [comment]
thanks @ajzbrun, I agree it's better to wait for @CatmanIta before making any change!

**Comment by ajzbrun** [comment]
@FrancyCavallari  yeah right, I've tried in Learn Polish version, but all the times it worked just fine. About the words quantity, I don't see anything in the code that indicates that wont work with less than 3 words, but could be...
No problem, let's wait for @CatmanIta validation to see how to follow this.

**Comment by FrancyCavallari** [comment]
I tried adding a word to Phrase_cheese and the sentence was displayed & played correctly...
![image](https://user-images.githubusercontent.com/17926293/174333740-b9aca423-f3d9-4c37-bae9-6f966cac42ca.png)
... but after a few round the game got stuck anyway. :-(
