### ISSUE TITLE
[DB Import] Importing phrases for Learn German always import English ones instead

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#399]
Importing from Google Sheet the Phreases, we should always use the column with the same name of the Learning Language
i.e. importing for Learn German should import the German column
@StefanoCecere, I assign this issue to @ajzbrun ¡, but if you prefer you can look into it yourself.

**Comment by ajzbrun** [comment]
Okay! Let me check it

**Comment by ajzbrun** [comment]
There was a LanguageCode reference inside the DatabaseLoader (hidden in inspector) that wasn't changing when importing the editions, that's why it was always taking the English version of phrases. I added a quick match from the selected content edition to the appropiate LanguageCode on that reference.
Seems to be working okay now. I wait for validation @FrancyCavallari
