### ISSUE TITLE
[Arabic] [Profile Creation] New avatars are used... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#82]
![image](https://user-images.githubusercontent.com/17926293/98660021-1a8b8980-2345-11eb-8171-5b64ff230cac.png)

Should we keep only the old avatars for retrocompatibility?  
Or better have both: old avatars for old profile, new avatars for new profiles?

**Comment by FrancyCavallari** [comment]
Should we keep the age?
![image](https://user-images.githubusercontent.com/17926293/98660171-4870ce00-2345-11eb-862c-aef2596e7518.png)

**Comment by CatmanIta** [comment]
I already support both, but the system changed so much I think we'd better use the new ones (and they are also cuter)

Age/sex are already options that can be changed in the edition configuration

**Comment by FrancyCavallari** [comment]
not sure... we have thousands of players using/ used to the old avatars

**Comment by CatmanIta** [comment]
Note that it would matter only if you created a new profile, existing avatars are kept the same.
I think that since we are upgrading the version we should not keep two different systems to build the avatar (it would mean we should mantain both, I am not sure the old one works anymore in the current version, I think we overwrote it with the new one)

**Comment by CatmanIta** [comment]
I tested it and it is not working, I remember Daniele re-did the scene but if we want it again we'd need to go back and find the old version in the repositories. Sounds like a work not worth doing to me.

**Comment by FrancyCavallari** [comment]
ok
