### ISSUE TITLE
[Arabic] Parental Gate is not ok....

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#85]
... and it should be in 2 languages (Arabic + English)
![image](https://user-images.githubusercontent.com/17926293/98661471-c681a480-2346-11eb-955f-fd44d6f61be2.png)

**Comment by FrancyCavallari** [comment]
set to URGENT because now it's impossible to create a Demo Profile

**Comment by CatmanIta** [comment]
We deprecated this as it was hardcoded, the issue is that we need somewhere to store the different 'text parts' for the Native language too: colors and numbers. We get them from WordData, but that is only available for the Learning language!

We should probably add to the Localization IDs also the numbers and colors so we can reuse them regardless of whether it is a learning or native language

**Comment by CatmanIta** [comment]
I remade the panel so we can support both "learning-only" and "native+learning".
Note that the above remains, however, so we need to add the text to LocalizationID before implementing the rest!

**Comment by CatmanIta** [comment]
I am now using the 'Subtitles' language code instead of the Native one, as that is more appropriate. I set Arabic to use English as Subtitles, as per the original version.

![image](https://user-images.githubusercontent.com/3244662/98951415-82370580-24fa-11eb-99f4-50836a27df42.png)

Note that the current text is this one, the "forced text" one, so it should be changed to the dynamic one in the localization.

**Comment by CatmanIta** [comment]
Temporarly, we'll use the fixed sequence so we can test on android

**Comment by CatmanIta** [comment]
I already had supported this, check in the AppConfig.
Pushing it with the forced sequence enabled for now.
It's 5 times the first, 1 time the second

![image](https://user-images.githubusercontent.com/3244662/101907505-f2e54680-3bba-11eb-8060-d0ebed1db275.png)

**Comment by FrancyCavallari** [comment]
Added LocaIDs:

UI_Number_1
UI_Number_2
UI_Number_3
UI_Number_4
UI_Number_5

UI_Antura_Color_Green
....
