### ISSUE TITLE
[Arabic] Minigames icons and badges are missing

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#87]
![image](https://user-images.githubusercontent.com/17926293/98661819-3e4fcf00-2347-11eb-8ccf-1a40e43505bf.png)

**Comment by CatmanIta** [comment]
This is because they were not in the _config/Resources/arabic/Images/GameIcons folder.
This is controlled locally as we now use Resources to load the different images.
We can fix this by moving the GameIcons from arabic_ea4s to arabic.

Didn't we have a separate repository or sub-repo for the per-edition data?

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/98949533-266b7d00-24f8-11eb-8f36-4f6e9c4ce591.png)
Note that not all badges seem to be present anyway
