### ISSUE TITLE
[Arabic] Words categories are missing in vocabulary...

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura#88]
![image](https://user-images.githubusercontent.com/17926293/98661935-67705f80-2347-11eb-8c9f-8ab0e44eb964.png)

... should we import the Words DB?

**Comment by FrancyCavallari** [comment]
No, it seems WordDB is ok but the categories are all empty

**Comment by CatmanIta** [comment]
The culprit is UI_WordCat_Math, there is no instance of it in the LocalizationTable.

I fixed the bug there and now it displays ERROR when something is missing.

Note thta we are also missing these, they seem to not be missing in the table, but the text is not set.

![image](https://user-images.githubusercontent.com/3244662/98939679-151b7400-24ea-11eb-85cc-0d00765db23d.png)
